const presetTalents = {
  wrath: {
    suppression: 5,
    improvedCorruption: 5,
    improvedDrainSoul: 2,
    improvedLifeTap: 2,
    amplifyCurse: 1,
    grimReach: 1,
    nightfall: 2,
    empoweredCorruption: 3,
    shadowEmbrace: 5,
    siphonLife: 1,
    shadowMastery: 5,
    contagion: 5,
    malediction: 3,
    improvedShadowBolt: 5,
    bane: 5,
    devastation: 5,
    shadowburn: 1,
    intensity: 2,
    destructiveReach: 2
  },
  ns: {
    suppression: 5,
    improvedCorruption: 5,
    improvedDrainSoul: 2,
    improvedLifeTap: 2,
    amplifyCurse: 1,
    grimReach: 1,
    nightfall: 2,
    empoweredCorruption: 3,
    shadowEmbrace: 5,
    siphonLife: 1,
    shadowMastery: 5,
    contagion: 5,
    malediction: 3,
    improvedShadowBolt: 5,
    bane: 5,
    devastation: 5,
    shadowburn: 1,
    intensity: 2,
    destructiveReach: 2,
    ruin: 1
  }
}
