const presetTalents = {
  wrath: {
    convection: 5,
    concussion: 5,
    elementalWarding: 3,
    callOfFlame: 1,
    elementalFocus: 1,
    callOfThunder: 5,
    stormReach: 2,
    elementalFury: 1,
    unrelentingStorm: 3,
    elementalPrecision: 3,
    lightningMastery: 5,
    elementalMastery: 1,
    lightningOverload: 5,
    totemOfWrath: 1,
    tidalFocus: 5,
    improvedReincarnation: 1,
    totemicFocus: 5,
    naturesGuidance: 3,
    totemicMastery: 1,
    tidalMastery: 5
  },
  ns: {
    convection: 5,
    concussion: 5,
    elementalWarding: 3,
    callOfFlame: 1,
    elementalFocus: 1,
    callOfThunder: 5,
    eyeOfTheStorm: 3,
    stormReach: 2,
    elementalFury: 1,
    lightningMastery: 5,
    elementalMastery: 1,
    elementalShields: 3,
    lightningOverload: 5,
    tidalFocus: 5,
    ancestralHealing: 3,
    totemicFocus: 5,
    naturesGuidance: 1,
    totemicMastery: 1,
    tidalMastery: 5,
    naturesSwiftness: 1
  }
}
